--vim.cmd [[packadd packer.nvim]]
--
--return require('packer').startup(function(use)
--  -- Packer can manage itself
--  use 'wbthomason/packer.nvim'
--
--  use('arcticicestudio/nord-vim', { branch = 'develop' })
--  use('nvim-treesitter/nvim-treesitter', {run = ':TSUpdate'})
--  use('fatih/vim-go')
--  use('tpope/vim-fugitive')
--  use('tpope/vim-surround')
--  use {
--	  'VonHeikemen/lsp-zero.nvim',
--	  branch = 'v3.x',
--	  requires = {
--		  --- Uncomment the two plugins below if you want to manage the language servers from neovim
--		  {'williamboman/mason.nvim'},
--		  {'williamboman/mason-lspconfig.nvim'},
--
--
--		  {'neovim/nvim-lspconfig'},
--		  {'hrsh7th/nvim-cmp'},
--		  {'hrsh7th/cmp-nvim-lsp'},
--		  {'hrsh7th/cmp-nvim-lsp-signature-help'},
--		  {'L3MON4D3/LuaSnip'},
--	  }
--  }
--  use('vim-airline/vim-airline')
--  use('vim-airline/vim-airline-themes')
--  use('HiPhish/rainbow-delimiters.nvim')
--  use('nvim-treesitter/nvim-treesitter-context')
--use {
--  'nvim-telescope/telescope.nvim', tag = '0.1.6',
---- or                            , branch = '0.1.x',
--  requires = { {'nvim-lua/plenary.nvim'} }
--}
--use {'ntpeters/vim-better-whitespace'}
-- end)
